### PR TITLE
fix: window check for Electron

### LINKED ISSUE #1592: `isWindow` function doesn't work correctly in Electron
When you are working in Electron, the string representation of window returns `[object global]`, not `[object Window]` what you expect. Because of this, the overlay component does not work correctly in Electron
https://github.com/floating-ui/floating-ui/blob/ae2e56e751d247d81b162112cd46238c5290e685/packages/dom/src/utils/window.ts#L1-L3

### PR DESCRIPTION
**Pull request by atomiks**
Closes #1592

### CODE REVIEW

File: packages/dom/src/utils/getNodeScroll.ts [hunk 1]
```diff
@@ -1,16 +1,16 @@
 import {NodeScroll} from '../types';
-import {isWindow} from './window';
+import {isElement} from './is';
 
 export function getNodeScroll(element: Element | Window): NodeScroll {
-  if (isWindow(element)) {
+  if (isElement(element)) {
```
Comment (atomiks) [inline packages/dom/src/utils/getNodeScroll.ts:5]: This change alone makes it work like Popper, but as I mentioned I think there's likely an issue with iframes in Electron if we also don't change `isWindow` check. That means this isn't strictly necessary but it's probably safer

File: packages/dom/src/utils/window.ts [hunk 2]
```diff
@@ -1,5 +1,11 @@
 export function isWindow(value: any): value is Window {
-  return value?.toString() === '[object Window]';
+  return (
+    value &&
+    value.document &&
+    value.location &&
+    value.alert &&
+    value.setInterval
+  );
```
Comment (atomiks) [inline packages/dom/src/utils/window.ts:8]: @deface-37 does this check solve the issue?

Comment (deface-37) [reply packages/dom/src/utils/window.ts:8]: Yes, it does. Thanks
