### PR TITLE
getOverflowAncestors: traverse into iframe parent

### LINKED ISSUE #2518: getOverflowAncestors should traverse through parent iframes
**Describe the bug**
Since #2043 the `getBoundingClientRect` DOM util function traverses all the parent iframes and adds their offsets, so that the computed offset is always relative to the top-level document.

But it turns out that one piece is missing for full seamless iframe support. The `autoUpdate` function has `ancestorResize` and `ancestorScroll` options. They cause that all ancestor scrolling elements get `resize` and `scroll` listeners and that position is recomputed when the reference and floating element get scrolled relative to each other.

But the `getOverflowAncestors` DOM util function doesn't traverse through parent iframes. It stops when it reaches the current frame's document element. If the iframe is inside a scrolling container:
```
<div id="floating">popover</div>
<div id="scrolling" style="overflow: auto">
  <iframe>
    <div id="reference">anchor</div>
  </iframe>
</div>
```
Then when the `#scrolling` contents scroll, then `autoUpdate` doesn't catch that.

**To Reproduce**
I don't have a minimal repro example yet. I'm interested in working on a fix, together with tests and all.

Cc @ciampo

### PR DESCRIPTION
**Pull request by jsnajdr**
Fixes #2518.

When `getOverflowAncestors` reaches the `window` object, it checks whether there is `window.frameElement` and continues traversing up into the iframe's parent.

TODO before this is shippable:
- add tests
- verify usage in `getClippingElementAncestors`. Do we also want to traverse into iframe's parent there?

### CODE REVIEW

File: packages/utils/dom/src/index.ts [hunk 1]
```diff
@@ -168,7 +168,8 @@ export function getOverflowAncestors(
     return list.concat(
       win,
       win.visualViewport || [],
-      isOverflowElement(scrollableAncestor) ? scrollableAncestor : []
+      isOverflowElement(scrollableAncestor) ? scrollableAncestor : [],
+      win.frameElement ? getOverflowAncestors(win.frameElement) : [],
```
Comment (tyxla) [inline packages/utils/dom/src/index.ts:172]: This could use a unit test - there is already an [existing test suite](https://github.com/floating-ui/floating-ui/blob/master/packages/utils/test/getOverflowAncestors.test.ts) for `getOverflowAncestors()`. 

We might need to configure [loading of subresources](https://github.com/jsdom/jsdom#loading-subresources) because `jsdom` by default won't load any subresources like iframes, and for an element inside the iframe, `node.ownerDocument.defaultView` will be equal to the parent `window` object.

File: packages/utils/test/getOverflowAncestors.test.ts [hunk 2]
```diff
@@ -65,3 +65,20 @@ test('does treat display: inline-block elements as overflow ancestors', () => {
...
+
+test('returns overflow ancestors in iframe parents', () => {
+  const scroll = document.createElement('div');
+  scroll.style.overflow = 'scroll';
+  const iframe = document.createElement('iframe');
+  const test = document.createElement('div');
+
+  document.body.append(scroll);
+  scroll.append(iframe);
+  iframe.contentDocument!.body.append(test);
```
Comment (tyxla) [inline packages/utils/test/getOverflowAncestors.test.ts:77]: We may need a `no-non-null-assertion` ignore here.

File: packages/utils/dom/src/index.ts (hunk 1 above)
Comment (tyxla) [reply packages/utils/dom/src/index.ts:172]: Nice, great to hear that it wasn't a problem 👍

File: packages/utils/test/getOverflowAncestors.test.ts [hunk 3]
```diff
@@ -65,3 +65,20 @@ test('does treat display: inline-block elements as overflow ancestors', () => {
     window,
   ]);
 });
+
+test('returns overflow ancestors in iframe parents', () => {
```
Comment (tyxla) [inline packages/utils/test/getOverflowAncestors.test.ts:69]: Thanks for adding the test 🙌

**Review by tyxla — APPROVED** [review]
This looks great to me 👍 🚀 

Looking forward to getting this landed so we can remove the extra custom listeners in [#54286](https://github.com/WordPress/gutenberg/pull/54286)

File: packages/utils/test/getOverflowAncestors.test.ts (hunk 2 above)
Comment (jsnajdr) [reply packages/utils/test/getOverflowAncestors.test.ts:77]: `iframe.contentDocument` can be `null`, but by appending the element into the `document.body` structure, we are "attaching" it and it gets loaded. Then `contentDocument` and `contentWindow` get a reliable non-null value. But this certaintly can't be expressed in types.

Comment (atomiks) [reply packages/utils/test/getOverflowAncestors.test.ts:77]: This looks good, but to prevent warnings appearing here, can you appease the checker?

Comment (jsnajdr) [reply packages/utils/test/getOverflowAncestors.test.ts]: Warning fixed :+1:

**Comment by jsnajdr** [comment]
Thanks @atomiks for merging the patch so quickly :+1: There might be, however, something wrong with the release. The `getOverflowAncestors` function is part of the `@floating-ui/utils` package, but only the `@floating-ui/dom` got released.

**Comment by atomiks** [comment]
oh 🤦 I forgot that function was moved out into the `utils` package, only `utils` needed to be released. I'll fix it in a second.
